#url: https://y7kim.github.io

#url: http://www.lbkadvertising.com

url:
baseurl:

# Site settings
title: "Lubbock's digital advertising experts | LBK advertising."
email: joe@lbkadvertising.com
description: "We run Facebook and Google ad campaigns to help local Lubbock businesses reach more customers and grow."

# Livereload
livereload: true

# Build settings
markdown: kramdown
permalink: pretty
